// This file is generated by src/actors/_scripts/generate-actor-migrations.ts.
// Source of truth is drizzle-kit output under ./drizzle (meta/_journal.json + *.sql).
// Do not hand-edit this file.

const journal = {
  entries: [
    {
      idx: 0,
      when: 1770924376062,
      tag: "0000_stormy_the_hunter",
      breakpoints: true,
    },
    {
      idx: 1,
      when: 1770947252449,
      tag: "0001_wild_carlie_cooper",
      breakpoints: true,
    },
    {
      idx: 2,
      when: 1771276338465,
      tag: "0002_far_war_machine",
      breakpoints: true,
    },
    {
      idx: 3,
      when: 1771369000000,
      tag: "0003_busy_legacy",
      breakpoints: true,
    },
  ],
} as const;

export default {
  journal,
  migrations: {
    m0000: `CREATE TABLE \`branches\` (
	\`branch_name\` text PRIMARY KEY NOT NULL,
	\`commit_sha\` text NOT NULL,
	\`worktree_path\` text,
	\`parent_branch\` text,
	\`diff_stat\` text,
	\`has_unpushed\` integer,
	\`conflicts_with_main\` integer,
	\`first_seen_at\` integer,
	\`last_seen_at\` integer,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`pr_cache\` (
	\`branch_name\` text PRIMARY KEY NOT NULL,
	\`pr_number\` integer NOT NULL,
	\`state\` text NOT NULL,
	\`title\` text NOT NULL,
	\`pr_url\` text,
	\`pr_author\` text,
	\`is_draft\` integer,
	\`ci_status\` text,
	\`review_status\` text,
	\`reviewer\` text,
	\`fetched_at\` integer,
	\`updated_at\` integer NOT NULL
);
`,
    m0001: `CREATE TABLE \`repo_meta\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`remote_url\` text NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE \`branches\` DROP COLUMN \`worktree_path\`;`,
    m0002: `CREATE TABLE \`task_index\` (
	\`task_id\` text PRIMARY KEY NOT NULL,
	\`branch_name\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
`,
    m0003: `ALTER TABLE \`branches\` ADD \`tracked_in_stack\` integer;`,
  } as const,
};
