use std::fs;
use std::io::Read as _;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::browser_errors::BrowserProblem;
use crate::browser_types::{BrowserContextCreateRequest, BrowserContextInfo};

/// Metadata stored alongside each browser context directory.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct ContextMeta {
    id: String,
    name: String,
    created_at: String,
}

const META_FILE: &str = "context.json";

/// Validate that a context_id is a valid hex string (generated by us) and that
/// the resulting path does not escape the base directory.  Returns the
/// validated, canonical context directory path on success.
pub fn validate_context_id(base: &Path, context_id: &str) -> Result<PathBuf, BrowserProblem> {
    // Only hex characters are valid – rejects ../,  %2F, etc.
    if !context_id.chars().all(|c| c.is_ascii_hexdigit()) || context_id.is_empty() {
        return Err(BrowserProblem::not_found(format!(
            "browser context '{context_id}' not found"
        )));
    }

    let context_dir = base.join(context_id);

    // Defence-in-depth: even after the regex check, canonicalize and verify
    // the resolved path is still under the base directory.
    if context_dir.exists() {
        let canonical = context_dir.canonicalize().map_err(|e| {
            BrowserProblem::internal_error(format!("failed to canonicalize context path: {e}"))
        })?;
        let canonical_base = base.canonicalize().map_err(|e| {
            BrowserProblem::internal_error(format!("failed to canonicalize base path: {e}"))
        })?;
        if !canonical.starts_with(&canonical_base) {
            return Err(BrowserProblem::not_found(format!(
                "browser context '{context_id}' not found"
            )));
        }
    }

    Ok(context_dir)
}

/// Return the base directory that holds all browser context directories.
pub fn contexts_base_dir(state_dir: &Path) -> PathBuf {
    state_dir.join("browser-contexts")
}

/// List all browser contexts stored on disk.
pub fn list_contexts(state_dir: &Path) -> Result<Vec<BrowserContextInfo>, BrowserProblem> {
    let base = contexts_base_dir(state_dir);
    if !base.exists() {
        return Ok(Vec::new());
    }

    let mut contexts = Vec::new();
    let entries = fs::read_dir(&base).map_err(|e| {
        BrowserProblem::internal_error(format!("failed to read contexts directory: {e}"))
    })?;

    for entry in entries {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let meta_path = path.join(META_FILE);
        if !meta_path.exists() {
            continue;
        }
        let meta_bytes = match fs::read(&meta_path) {
            Ok(b) => b,
            Err(_) => continue,
        };
        let meta: ContextMeta = match serde_json::from_slice(&meta_bytes) {
            Ok(m) => m,
            Err(_) => continue,
        };
        let size_bytes = dir_size(&path);
        contexts.push(BrowserContextInfo {
            id: meta.id,
            name: meta.name,
            created_at: meta.created_at,
            size_bytes: Some(size_bytes),
        });
    }

    contexts.sort_by(|a, b| a.created_at.cmp(&b.created_at));
    Ok(contexts)
}

/// Create a new browser context directory with metadata.
pub fn create_context(
    state_dir: &Path,
    request: BrowserContextCreateRequest,
) -> Result<BrowserContextInfo, BrowserProblem> {
    let id = generate_context_id();
    let base = contexts_base_dir(state_dir);
    let context_dir = base.join(&id);

    fs::create_dir_all(&context_dir).map_err(|e| {
        BrowserProblem::internal_error(format!("failed to create context directory: {e}"))
    })?;

    let now = chrono::Utc::now().to_rfc3339();
    let meta = ContextMeta {
        id: id.clone(),
        name: request.name.clone(),
        created_at: now.clone(),
    };

    let meta_bytes = serde_json::to_vec_pretty(&meta).map_err(|e| {
        BrowserProblem::internal_error(format!("failed to serialize context metadata: {e}"))
    })?;

    fs::write(context_dir.join(META_FILE), meta_bytes).map_err(|e| {
        BrowserProblem::internal_error(format!("failed to write context metadata: {e}"))
    })?;

    Ok(BrowserContextInfo {
        id,
        name: request.name,
        created_at: now,
        size_bytes: Some(0),
    })
}

/// Delete a browser context directory.
pub fn delete_context(state_dir: &Path, context_id: &str) -> Result<(), BrowserProblem> {
    let base = contexts_base_dir(state_dir);
    let context_dir = validate_context_id(&base, context_id)?;

    if !context_dir.exists() {
        return Err(BrowserProblem::not_found(format!(
            "browser context '{context_id}' not found"
        )));
    }

    fs::remove_dir_all(&context_dir).map_err(|e| {
        BrowserProblem::internal_error(format!("failed to delete context directory: {e}"))
    })?;

    Ok(())
}

/// Generate a hex-encoded random ID for a browser context.
fn generate_context_id() -> String {
    let mut bytes = [0u8; 16];
    if let Ok(mut file) = fs::File::open("/dev/urandom") {
        if file.read_exact(&mut bytes).is_ok() {
            return hex_encode(&bytes);
        }
    }
    // Fallback: timestamp + pid
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let pid = std::process::id() as u128;
    bytes = (now ^ (pid << 64)).to_le_bytes();
    hex_encode(&bytes)
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Recursively compute the size of a directory in bytes.
fn dir_size(path: &Path) -> u64 {
    let mut total = 0u64;
    if let Ok(entries) = fs::read_dir(path) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                total += dir_size(&p);
            } else if let Ok(meta) = p.metadata() {
                total += meta.len();
            }
        }
    }
    total
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_create_and_list_contexts() {
        let tmp = TempDir::new().unwrap();
        let state_dir = tmp.path();

        // Initially empty
        let contexts = list_contexts(state_dir).unwrap();
        assert!(contexts.is_empty());

        // Create a context
        let info = create_context(
            state_dir,
            BrowserContextCreateRequest {
                name: "test-profile".to_string(),
            },
        )
        .unwrap();
        assert_eq!(info.name, "test-profile");
        assert!(!info.id.is_empty());

        // List shows it
        let contexts = list_contexts(state_dir).unwrap();
        assert_eq!(contexts.len(), 1);
        assert_eq!(contexts[0].name, "test-profile");
        assert_eq!(contexts[0].id, info.id);
    }

    #[test]
    fn test_delete_context() {
        let tmp = TempDir::new().unwrap();
        let state_dir = tmp.path();

        let info = create_context(
            state_dir,
            BrowserContextCreateRequest {
                name: "to-delete".to_string(),
            },
        )
        .unwrap();

        delete_context(state_dir, &info.id).unwrap();

        let contexts = list_contexts(state_dir).unwrap();
        assert!(contexts.is_empty());
    }

    #[test]
    fn test_delete_nonexistent_context() {
        let tmp = TempDir::new().unwrap();
        let result = delete_context(tmp.path(), "nonexistent");
        assert!(result.is_err());
    }

    #[test]
    fn test_delete_context_path_traversal_dotdot() {
        let tmp = TempDir::new().unwrap();
        let result = delete_context(tmp.path(), "../../../tmp");
        assert!(result.is_err());
    }

    #[test]
    fn test_delete_context_path_traversal_encoded() {
        let tmp = TempDir::new().unwrap();
        let result = delete_context(tmp.path(), "..%2F..%2Ftmp");
        assert!(result.is_err());
    }

    #[test]
    fn test_delete_context_valid_hex_not_found() {
        let tmp = TempDir::new().unwrap();
        let result = delete_context(tmp.path(), "abcdef0123456789");
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_context_id_rejects_empty() {
        let tmp = TempDir::new().unwrap();
        let base = contexts_base_dir(tmp.path());
        assert!(validate_context_id(&base, "").is_err());
    }

    #[test]
    fn test_validate_context_id_rejects_slashes() {
        let tmp = TempDir::new().unwrap();
        let base = contexts_base_dir(tmp.path());
        assert!(validate_context_id(&base, "abc/def").is_err());
        assert!(validate_context_id(&base, "abc\\def").is_err());
    }
}
